name: Custom Release Tag and Publish

on:
  workflow_dispatch: # Manual triggering

jobs:
  create_and_publish_release:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch latest tags
        run: git fetch --tags origin

      - name: Set old tag
        id: set_old_tag
        run: echo "::set-output name=old_tag::$(git describe --tags --abbrev=0)"

      - name: Set new tag name
        id: set_new_tag_name
        run: echo "::set-output name=new_tag_name::TEST-DEV_$(date +'%dth-%b_%H-%M%p')"

      - name: Create new tag from old tag
        run: git tag ${{ steps.set_new_tag_name.outputs.new_tag_name }} ${{ steps.set_old_tag.outputs.old_tag }}

      - name: Push new tag to repository
        run: git push origin ${{ steps.set_new_tag_name.outputs.new_tag_name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.set_new_tag_name.outputs.new_tag_name }}
          release_name: Release ${{ steps.set_new_tag_name.outputs.new_tag_name }}
          draft: false
          prerelease: false
