name: Manual Release Workflow

on:
  workflow_dispatch: # Manual triggering

jobs:
  release:
    name: Create and Publish Custom Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit hash
        id: get_commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Get previous tag
        id: get_previous_tag
        run: |
          git fetch --tags
          echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"

      - name: Create Custom Release
        id: create_release
        run: |
          previous_tag=${{ steps.get_previous_tag.outputs.previous_tag }}
          current_tag=${{ github.event.inputs.tag }}
          echo "Comparing changes between $previous_tag and $current_tag"
          # Add your custom steps to create the release with the desired tag

      - name: Publish Release
        id: publish_release
        run: |
          # Add your steps to publish the release (e.g., create release notes, upload assets, etc.)
