name: Publish Release Workflow

on:
  workflow_dispatch: # Manual triggering

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get previous tag
        id: get_previous_tag
        run: |
          git fetch --tags
          previous_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          echo "::set-output name=previous_tag::$previous_tag"

      - name: Create Custom Release Tag
        id: create_custom_tag
        run: |
          previous_tag=${{ steps.get_previous_tag.outputs.previous_tag }}
          current_date=$(date +%d)
          current_month=$(date +%m)
          current_time_minutes=$(date +%M)
          current_time_seconds=$(date +%S)
          custom_tag="TEST_${current_date}-${current_month}-${current_time_minutes}-${current_time_seconds}"
          echo "Custom tag: $custom_tag"
          git tag $custom_tag $previous_tag
          git push origin $custom_tag

      - name: Publish Release
        id: publish_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.create_custom_tag.outputs.custom_tag }} # Use the custom tag as the tag name
          release_name: Release for ${{ steps.create_custom_tag.outputs.custom_tag }}
          body: Release created automatically from GitHub Actions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
